[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# jp help
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# neosnippet defines
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'

# -------------- dark powered ---------------

# deoplete
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
depends = 'context_filetype.vim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'

# deoppet
[[plugins]]
repo = 'Shougo/deoppet.nvim'

# --------------- color setting --------------

[[plugins]]
repo = 'wadackel/vim-dogrun'
hook_add = '''
	colorscheme dogrun
'''

# ---------------- status -----------------

# airline
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = 'vim-airline-themes'
hook_add = '''
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline_theme = 'minimalist'
  nmap <C-o> <Plug>AirlineSelectPrevTab
	nmap <C-p> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# ---------------- LSP ----------------------

# LanguageClient
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'zsh install.sh'
hook_add = '''
  source ~/.config/nvim/plugins/LCnvim.rc.vim
'''
# ------------------------------------------

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft=['tex']
hook_source='''
  let g:vimtex_view_general_viewer = 'displayline'
  let g:vimtex_view_general_options = '-r @line @pdf @tex'
'''
