[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# color setting
[[plugins]]
repo = 'wadackel/vim-dogrun'
hook_add = '''
	colorscheme dogrun
'''
# status setting
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#tabline#buffer_idx_mode = 1
	let g:airline_theme = 'minimalist'
  nmap <C-o> <Plug>AirlineSelectPrevTab
	nmap <C-p> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


