[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# jp help
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# status 
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = 'vim-airline-themes'
hook_add = '''
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline_theme = 'minimalist'
  nmap <C-o> <Plug>AirlineSelectPrevTab
	nmap <C-p> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugins/LCnvim.rc.vim
'''

# neosnippet defines
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# ----------------dark powered----------------------
# deoplete
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
depends = 'context_filetype.vim'
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoppet.nvim'
#---------------------------------------------------

# color setting
[[plugins]]
repo = 'wadackel/vim-dogrun'
hook_add = '''
	colorscheme dogrun
'''
