
# parentheses
[[plugins]]
repo = 'cohama/lexima.vim'

# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet'
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_add = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''
#----------Rust lang-------------
[[plugins]]
repo = 'rust-lang/rust.vim'
depends = ['tagbar']
on_ft = ['rust']
hook_add = '''
	let g:rustfmt_autosave = 1
'''
#-------------------------------

